# Generated by Django 6.0.7 on 2026-07-09 04:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codename', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='El codename solo puede contener letras minúsculas, números y guiones bajos.', regex='^[a-z0-9]+(?:_[a-z0-9]+)*$')])),
                ('timezone', models.CharField(default='America/Bogota', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='callcenters', to='clients.client')),
            ],
        ),
    ]
