# Generated by Django 6.0.7 on 2026-07-09 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('callcenters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Mon', 'Lunes'), ('Tue', 'Martes'), ('Wed', 'Miércoles'), ('Thu', 'Jueves'), ('Fri', 'Viernes'), ('Sat', 'Sábado'), ('Sun', 'Domingo')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('callcenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_intervals', to='callcenters.callcenter')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='schedule_start_before_end'), models.UniqueConstraint(fields=('callcenter', 'weekday', 'start_time', 'end_time'), name='unique_schedule_interval')],
            },
        ),
    ]
