# Generated by Django 6.0.7 on 2026-07-09 16:16
from django.db import migrations


CREATE_VIEW_SQL = """
CREATE VIEW schedules_asterisk_schedule_legacy AS
SELECT
    CONCAT(
        '/horario/',
        callcenter.codename,
        '/',
        schedule.weekday
    ) AS astdb_key,
    STRING_AGG(
        TO_CHAR(schedule.start_time, 'HH24:MI')
        || '-'
        || TO_CHAR(schedule.end_time, 'HH24:MI'),
        '|'
        ORDER BY schedule.start_time, schedule.end_time
    ) AS schedule_value
FROM schedules_scheduleinterval AS schedule
INNER JOIN callcenters_callcenter AS callcenter
    ON callcenter.id = schedule.callcenter_id
WHERE callcenter.is_active = TRUE
GROUP BY
    callcenter.codename,
    schedule.weekday;
"""


DROP_VIEW_SQL = """
DROP VIEW IF EXISTS schedules_asterisk_schedule_legacy;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_VIEW_SQL,
            reverse_sql=DROP_VIEW_SQL,
        ),
    ]
