# Generated by Django 6.0.7 on 2026-07-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_schedulechangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulechangelog',
            name='audio_key',
            field=models.CharField(choices=[('schedule_changed', 'Horario modificado'), ('temporarily_unavailable', 'Atención no disponible'), ('special_day', 'Festivo o evento especial')], default='schedule_changed', max_length=40),
        ),
    ]
